# Introducción a NumPy

La librería NumPy proporciona una interfaz para guardar y operar sobre arreglos de datos. Estos arreglos en NumPy proporcionan muchas más operaciones y eficiencia en la manipulación y manejo de los arreglos conforme estos incrementan en tamaño.

In [2]:
import numpy
numpy.__version__

'1.16.2'

In [3]:
import numpy as np

## Acerca de la Documentación

In [6]:
# Para desplegar la documentación
np?

# Tipos de Datos en Python

- Lenguajes de tipado estático como C o Java requieren que cada vriable sea declarada explicitamente
- Python en un lenguaje de tipado dinámico y no requiere ésta especificación Por ejemplo en C especificamos una operación como sigue:

In [ ]:
# /* codigo en C */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}

En Python la operación equivalente puede escribirse de la siguiente forma:

In [10]:
# codigo en Python
result = 0
for i in range(100):
    result += i

In [11]:
result

4950

La diferencia principal es
- en C el tipo de cada variable debe especificarse explicitamente
- en Python el tipo de cada variable es infrido dinámicamente

De este modo, en Python podemos asignar cualquier tipo de datos a cualquier variable

In [12]:
# codigo Python
x = 4
x = "four"

El equivalente en C sería como sigue, sin embargo, tendría errores de compilación o consecuencias inesperadas:

In [ ]:
/* codigo C */
int x = 4;
x = "four";  // ERROR

- Las variables en Python son más que s+olo su valor
- Contienen información extra sonre el tipo de valor, es decir el tipo de dato que representan.

## Enteros en Python

- La implementacion standard de Python está escrita en C.
- Si definimos un entero en Python, $x = 10000$, $x$ es un apuntador a una estructura de C:


In [ ]:
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};


- Un entero en Python contiene cuatro partes:

- $ob$_$refcnt$, un contador que ayuda en la asignación y liberación de memoria
- $ob$_$type$, codifica el tipo de variable
- $ob$_$size$, especifica el amaño
- $ob$_$digit$, contiene el valor asignado que representa la variable.

## Listas en Python

Una lista es una estructura de datos que permite colectar objetos. Creamos una lista de enteros de la siguiente forma:

In [21]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
type(L[0])

int

O una lista de caracteres de texto:

In [24]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [25]:
type(L2[0])

str

Gracias al tipado dinámico podemos crear listas heterogéneas:

In [26]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

- Esta felixibilidad tiene un costo pues cada elemento en la lista contiene es una referencia a una estructura que define el objeto de Python.
- En el caso especial que todas las entradas son del mismo tipo habrá información redundante: - Sería mas eficiente usar un arreglo de tipo fijo

### Arreglos de Tipo Fijo en Python

- En Python hay diferentes opciones para guardar datos en buffers de tipo fijo
- El modulo interno $array$ (disponible a partir de Python 3.3) sirve para crear arreglos densos de tipo uniforme:


In [27]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Aquí $i$ indica que las entradas son enteros.
- El objeto $ndarray$ de la libreria NumPy es mucho mas útil ya que implementa operaciones sobre los datos contenidos.
- Antes de explorar estas operaciones, veamos diversas maneras de crear arreglos de NumPy
- Comenzamos con la manera standard de importar NumPy, usando el alias $np$:

In [28]:
import numpy as np

## Crear Arreglos a partir de Listas de Python

Podemos usar $np.array$ para crear arreglos a partir de listas:

In [29]:
# array de enteros:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

- A diferencia de las lista en Python, NumPy está restringif a arreglos que contienen el mismo tipo de datos
- Si los tipos no coinciden NumPy trata de ajustar (upcast, emitir) si es posible
- En el siguiente ejemplo, los enteros se emiten a punto flotante:



In [30]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

- Podemos indicar el tipo de datos del arreglo explicitamente usando la palabra $dtype$:

In [31]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

- Adiferencia de las listas, los arreglos de NumPy pueden ser explicitamente multi-dimensionales
- A continuación, una forma de inicializar un arreglo multidimensional usando una lista de listas:

In [34]:
# una lista "nested" resulta en un array multi-dimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

- Las listas interiores se toman como renglones del arreglo bidimensional resultante

## Creando Arreglos

- Para arreglos grandes, es más eficiente crearlos usando rutinas implementadas en NumPy:

In [35]:
# Crea arreglo de enteros de longitud-10 lleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
# Crea arreglo con puntos flotantes de dimensiones 3x5 (3 renglones, 5 columnas) lleno de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# Crea arreglo de 3x5 array lleno de 3.14
np.full((5, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [39]:
# Crea arreglo lleno con una secuencia lineal de numeros
# Empieza en 0, acaba en 20, en pasos de 2
# (similar a la funcion interna range())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
# Crea array de cinco valores igualmente espaciados entre 0 y 1
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
# Crea un arreglo de 3x3 con valores aleatorios
# distribuidos de manera uniforma entre 0 y 1
np.random.random((3, 3))

array([[0.56776587, 0.10942188, 0.74832939],
       [0.96632963, 0.80277326, 0.15417623],
       [0.36394076, 0.60434762, 0.68327382]])

In [44]:
# Crea un arreglo de 3x3 con valores aleatorios
# distribuidos de manera normal con media 0 y desviacion estandard 1
np.random.normal(0, 1, (3, 3))

array([[ 1.30869207, -1.28313937, -1.12781077],
       [-1.46249975,  0.81709154, -0.12896808],
       [-0.85144561, -0.51257939, -0.68517079]])

In [45]:
# Crea array de 3x3 de números enterros aleatorios tomados del intervalo [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 8, 8],
       [8, 3, 7],
       [0, 2, 2]])

In [47]:
# Crea matriz identidad de 3x3 (arreglo cuyas entradas son todas cero excepto las diagonales)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Crea un array de tres enteros sin valores especificos
# Los valores se toman de lo que exista en esa localizacion de la memoria
np.empty(3)

array([1., 1., 1.])

## Tipos de Datos Standard de NumPy

- Los arrays de NumPy contienen valores de un solo tipo, veamos cuales pueden ser
- NumPy está implementado en C, de modo que los tipos son similares a los usados en C, Fortran, y otros lenguajes relacionados
- La siguiente tabla enlista los tipos de datos standard de NumPy
- Cuando construyen un array se puede especificar el tipo usando texto:


In [49]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

- O usando el objeto de NumPy asociado:

In [50]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)