# Agregaciones: Min, Max, etc.

## Sumando los Valores de un Array

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

54.66754463165986

In [3]:
np.sum(L)

54.667544631659844

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

80.5 ms ± 985 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
576 µs ± 47.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Mínimo y Máximo

In [6]:
min(big_array), max(big_array)

(6.047513745333077e-07, 0.9999974842588348)

In [7]:
np.min(big_array), np.max(big_array)

(6.047513745333077e-07, 0.9999974842588348)

In [8]:
%timeit min(big_array)
%timeit np.min(big_array)

63.2 ms ± 999 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
551 µs ± 36.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
print(big_array.min(), big_array.max(), big_array.sum())

6.047513745333077e-07 0.9999974842588348 500397.99742097437


### Agregaciones multi dimensionales

In [10]:
M = np.random.random((3, 4))
print(M)

[[0.57616213 0.52273279 0.63766461 0.52089966]
 [0.59127926 0.49828958 0.65778783 0.12247745]
 [0.72162789 0.53603403 0.14010645 0.60881596]]


In [11]:
M.sum()

6.133877640548439

In [13]:
M.min(axis=0)

array([0.57616213, 0.49828958, 0.14010645, 0.12247745])

In [14]:
M.max(axis=1)

array([0.63766461, 0.65778783, 0.72162789])