# Comparaciones, máscaras y lógica booleana

## Operadores de comparación como ufuncs

- NumPy implementa operadores de comparación $<$ (menor que) y $>$ (mayor que)

In [3]:
x = np.array([1, 2, 3, 4, 5])

In [4]:
x < 3  # less than

array([ True,  True, False, False, False])

In [5]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [7]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [8]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [9]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [10]:
x == 3  # equal

array([False, False,  True, False, False])

In [11]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

Como en el caso de operadores aritmicos, los operadores de comparación son implementados como ufuncs en NumPy; por ejemplo, cuando escribes $x<3$, internamente NumPy usa $np.less(x,3)$.

In [12]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [13]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

## Usar las palabras reservadas $and$/$or$ contra usar los operadores $\&$/$|$

In [18]:
bool(42), bool(0)

(True, False)

In [19]:
bool(42 and 0)

False

In [20]:
bool(42 or 0)

True

In [21]:
bin(42)

'0b101010'

In [22]:
bin(59)

'0b111011'

In [23]:
bin(42 & 59)

'0b101010'

In [24]:
bin(42 | 59)

'0b111011'

In [25]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [26]:
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [27]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [28]:
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()